language: cpp
dist: trusty
compiler:
  - gcc

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - clang-6.0
        - llvm-6.0
script:
  - cmake .
  - make
  - make runtime_tests
  - make compiler_tests
