sudo: false
language: cpp
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++" CC="gcc"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
