sudo: false
language: cpp
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++" CC="gcc"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - cmake
    - libnuma-dev
    - libgtest-dev
script:
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd
    - mkdir build
    - cd build
    - cmake ..
    - make && make test
