sudo: required
language: cpp
services:
  - docker
before_install:
  - docker build -t furious . 
  - docker run  -itd --name build furious
script:
  - docker exec build cmake .
  - docker exec build make  
  - docker exec build make runtime_tests
  - docker exec build make compiler_tests
