
#ifndef _FURIOUS_CODEGEN_TOOLS_H_
#define _FURIOUS_CODEGEN_TOOLS_H_

#include "../../common/platform.h"
#include "../driver.h"
#include "../fcc_context.h"

/* AUTOGENERATED INCLUDES */
#include "autogen/cchar_ptr_array.h"
#include "autogen/fcc_decl_array.h"

#include <stdio.h>
#include <string.h>

struct fcc_subplan_t;
struct fcc_operator_t;

/**
 * @brief Tool used to extract the dependencies of an execution plan, which
 * include structures and headers including dependent structures
 */
struct fcc_deps_extr_t  
{
  cchar_ptr_array_t     m_incs;
  fcc_decl_array_t      m_decls;
};

void
fcc_deps_extr_init(fcc_deps_extr_t* deps_extr);

void
fcc_deps_extr_release(fcc_deps_extr_t* deps_extr);

void
fcc_deps_extr_extract(fcc_deps_extr_t* deps_extr,
                      const fcc_subplan_t* subplan);

////////////////////////////////////////////////
////////////////////////////////////////////////
////////////////////////////////////////////////


/**
 * \brief Tool to extract the components and tags used in an execution plan, which will
 * be used to declare the required variables in the generated code.
 */
struct fcc_vars_extr_t  
{
  fcc_decl_array_t  m_comp_decls;
  cchar_ptr_array_t m_tags;
  cchar_ptr_array_t m_refs;
  cchar_ptr_array_t m_comps;
};

void
fcc_vars_extr_init(fcc_vars_extr_t* vars_extr);

void
fcc_vars_extr_release(fcc_vars_extr_t* vars_extr);

void
fcc_vars_extr_extract(fcc_vars_extr_t* vars_extr,
                      const fcc_subplan_t* subplan);

////////////////////////////////////////////////
////////////////////////////////////////////////
////////////////////////////////////////////////

void
sanitize_name(char* str);

uint32_t
generate_table_name(const char* type_name,
                    char* buffer,
                    uint32_t buffer_length, 
                    const fcc_operator_t* op = nullptr);

uint32_t
generate_temp_table_name(const char* type_name,
                         char* buffer,
                         uint32_t buffer_length,
                         const fcc_operator_t* op = nullptr);

uint32_t
generate_ref_table_name(const char* ref_name,
                        char* buffer,
                        uint32_t buffer_length, 
                        const fcc_operator_t* op = nullptr);

uint32_t
generate_bittable_name(const char* tag_name,
                       char* buffer,
                       uint32_t buffer_length,
                       const fcc_operator_t* op = nullptr);

uint32_t
generate_table_iter_name(const char* table_name,
                         char* buffer,
                         uint32_t buffer_length,
                         const fcc_operator_t* op = nullptr);

uint32_t
generate_block_name(const char* type_name,
                    char* buffer,
                    uint32_t buffer_length,
                    const fcc_operator_t* op = nullptr);

uint32_t
generate_cluster_name(const fcc_operator_t* op,
                      char* buffer,
                      uint32_t buffer_length);

uint32_t
generate_ref_groups_name(const char* ref_name,
                         char* buffer,
                         uint32_t buffer_length, 
                         const fcc_operator_t* op);

uint32_t
generate_hashtable_name(const fcc_operator_t* op,
                        char* buffer,
                        uint32_t buffer_length);

uint32_t
generate_system_wrapper_name(const char* system_name,
                             uint32_t system_id,
                             char* buffer,
                             uint32_t buffer_length,
                             const fcc_operator_t* op = nullptr);

uint32_t
generate_global_name(const char* type_name,
                     char* buffer,
                     uint32_t buffer_length, 
                     const fcc_operator_t* op = nullptr);


#endif
